query biopsies {
  biopsies(order_by: { number: desc_nulls_last }) {
    id
    number
    sample
    entry_date
    macroscopic_date
    microscopic_date
    patient {
      id
      first_name
      last_name
    }
    reported_by {
      practitioner {
        id
        identifier
        first_name
        last_name
      }
    }
  }
}
