query GetBiopsies($limit: Int, $offset: Int) {
  biopsies(
    limit: $limit
    offset: $offset
    order_by: { number: desc_nulls_last }
  ) {
    id
    number
    sample
    entry_date
    macroscopic_date
    microscopic_date
    patient {
      id
      full_name
    }
  }
}
