mutation CreatePatient($patient: patients_insert_input!) {
  insert_patients_one(object: $patient) {
    id
    address
    birthdate
    first_name
    gender
    identifier
    last_name
    municipality {
      code
      name
      province_id
      province {
        code
        name
      }
    }
    municipality_id
  }
}
