mutation InsertBiopsy($biopsy: biopsies_insert_input!) {
  insert_biopsies_one(object: $biopsy) {
    id
    number
    sample
    entry_date
    macroscopic_date
    microscopic_date
    patient {
      id
      first_name
      last_name
    }
    reported_by {
      practitioner {
        id
        identifier
        first_name
        last_name
      }
    }
  }
}
