query GetPatients($limit: Int, $offset: Int) {
  patients_aggregate {
    aggregate {
      count
    }
  }
  patients(limit: $limit, offset: $offset, order_by: { created_at: desc }) {
    id
    identifier
    full_name
    birthdate
    address
    municipality {
      name
    }
  }
}
