mutation updatePatient($id: uuid!, $patient: patients_set_input) {
  update_patients(where: { id: { _eq: $id } }, _set: $patient) {
    returning {
      id
      address
      birthdate
      first_name
      gender {
        value
      }
      gender_id
      identifier
      last_name
      municipality {
        code
        name
        province_id
        province {
          code
          name
        }
      }
      municipality_id
    }
  }
}
